title: Vận Già Blog
description: Nơi chia sẻ những lượm lặt của Vận Già
author: Vận Già
github: https://github.com/vegetaz
about: Sharing Vận Già's odds and ends.
disqus_shortname: vegetaz
google_analytics: G-CTNX87JXNZ

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-facebook
    link: "https://www.facebook.com/vanfsn"
  - icon: fa-twitter
    link: "https://twitter.com/vanfsn"
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/vanz25"
  - icon: fa-stack-exchange
    link: "https://stackoverflow.com/users/7106855/vegetaz"
  - icon: fa-github
    link: "https://github.com/vegetaz"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
  - text: About Me
    url: /about/
  - text: Category
    url: /category/
  - text: My Projects
    url: /projects/
  - text: XML Feed
    url: /feed.xml

url: "https://vegetaz.github.io"
baseurl: ""
paginate: 25
per_page: 25
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
