# https://jekyllrb.com/docs/continuous-integration/github-actions/

name: Build and Deploy using GitHub Actions

on:
  push:
    branches: master  # Thay thế "main" bằng tên nhánh (trước năm 2020 là master)

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.5
        with:
          target_branch: 'gh-pages'
        evn:
           JEKYLL_PAT: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
           JEKYLL_ENV: production
