# https://jekyllrb.com/docs/continuous-integration/github-actions/

name: Build and Deploy Jekyll site to GitHub Pages using GitHub Actions

on:
  push:
    branches:
      - master  # Thay thế "main" bằng tên nhánh (trước năm 2020 là master)

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@2.0.5    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
